[package]
name = "mexmin"
version = "0.1.1"
authors = ["thyrc <thyrc@users.noreply.github.com>"]
edition = "2018"
publish = false
description = "Dump Maxmind GeoIP / GeoLite data"

[dependencies]
maxminddb = "0.13"
clap = "2"
